# Adapted from https://github.com/commercialhaskell/stack
language: nix
sudo: false

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work

matrix:
  fast_finish: true
  include:
    # Add build targets here
    - env: GHCVER=8.6.3 CACHE_NAME=8.6.3 BUILD_BINARY=1
      compiler: ": #stack 8.6.3"
      addons: {apt: {packages: [ghc-8.6.3], sources: [hvr-ghc]}}

    - env: GHCVER=8.6.3 CACHE_NAME=8.6.3-osx BUILD_BINARY=1
      os: osx
      compiler: ": #stack 8.6.3"
      addons: {apt: {packages: [ghc-8.6.3], sources: [hvr-ghc]}}

install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - ./.travis/install-ghr.sh
 - ./.travis/install-stack.sh

script:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - |
   set -ex
   # Run tests
   stack --no-terminal test --ghc-options="$GHC_OPTIONS"
   set +ex

after_success:
 - |
   # Build and ship binary
   ./.travis/attach-binary.sh
